### ISSUE TITLE
How do I change the commands?

### ISSUE THREAD

**Issue by ColePZ** [ethanent/hycord#1]
I want to change the commands, but I can't?

**Comment by JustOneMoreBlock** [comment]
https://github.com/ethanent/hycord/blob/master/index.js#L65-L67
_Change this for output of the commands._

https://github.com/ethanent/hycord/blob/master/index.js#L73
_Change the_ `player` _to your new command._

https://github.com/ethanent/hycord/blob/master/index.js#L73
_Change this for output of the commands._

**Comment by ethanent** [comment]
Thanks, @JustOneMoreBlock! 😀
